FROM vantruongt2/jmeter:jmeter-base

# Ports to be exposed from the container for JMeter Slaves/Server
EXPOSE 1099 50000

# Copy rmi keystore
COPY ./rmi_keystore.jks ${JMETER_HOME}/bin

# Application to run on starting the container
ENTRYPOINT $JMETER_HOME/bin/jmeter-server \
                        -Dserver.rmi.localport=50000 \
                        -Dserver_port=1099 \
                        -Djava.rmi.server.hostname=$LOCALIP