# 1
FROM jmeter-base

# 2
LABEL maintainer="tien.tran"

# 3 
ARG JMETER_VERSION="5.1"

ARG JMETER_INFLUXDB_WRITER_VERSION="1.0"
ARG JMETER_INFLUXDB_WRITER_NAME=JMeter-InfluxDB-Writer-${JMETER_INFLUXDB_WRITER_VERSION}.jar
ARG JMETER_PLUGIN_INFLUXDB_WRITER_URL=https://github.com/NovatecConsulting/JMeter-InfluxDB-Writer/releases/download/v-${JMETER_INFLUXDB_WRITER_VERSION}/${JMETER_INFLUXDB_WRITER_NAME}

# 4
ENV JMETER_HOME /opt/apache-jmeter-${JMETER_VERSION}
ENV JMETER_BIN  ${JMETER_HOME}/bin
ENV JMETER_PLUGINS_FOLDER ${JMETER_HOME}/lib/ext/

# 5
RUN    apk update \
	&& apk upgrade \
	&& apk add ca-certificates \
	&& update-ca-certificates \
            && apk add --update openjdk8-jre tzdata curl unzip bash \
            && cp /usr/share/zoneinfo/Europe/Rome /etc/localtime \
            && echo "Europe/Rome" >  /etc/timezone \
	&& rm -rf /var/cache/apk/*	

RUN apk add --no-cache nss

# 6
RUN curl -L --silent ${JMETER_PLUGIN_INFLUXDB_WRITER_URL} -o ${JMETER_PLUGINS_FOLDER}/${JMETER_INFLUXDB_WRITER_NAME}

# 7
ENV PATH $PATH:$JMETER_BIN

# 8
COPY launch.sh /

#9
WORKDIR ${JMETER_HOME}

#10
ENTRYPOINT ["/launch.sh"]
